# Generated by Django 4.1.5 on 2023-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
